SET(GCC_JSC_COMPILE_FLAGS "-D__STDC_LIMIT_MACROS=1 -DUCONFIG_ONLY_COLLATION=1")

# Disable JIT and assembly on older processors
if( ANDROID_ABI STREQUAL "armeabi" OR ANDROID_ABI STREQUAL "mips" OR ANDROID_ABI STREQUAL "armeabi-v7a" OR DISABLE_JIT )
    if ( NOT FORCE_JIT )
        SET(GCC_JSC_COMPILE_FLAGS "${GCC_JSC_COMPILE_FLAGS} -DENABLE_JIT=0 -DENABLE_YARR_JIT=0 -DENABLE_ASSEMBLER=0")
    endif()    
endif()

if( ANDROID_API LESS 18 )
    SET(GCC_JSC_COMPILE_FLAGS "${GCC_JSC_COMPILE_FLAGS} -Dlog2\\(x\\)=\\(log\\(x\\)\\/log\\(2\\)\\)")
endif()

SET( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} ${GCC_JSC_COMPILE_FLAGS}" )

FIND_LIBRARY( ANDROID_LOG_LIBRARY log )

set(LIB_INSTALL_DIR "${ANDROID_ABI}")

list(APPEND JavaScriptCore_SOURCES
    android/JSContext.cpp
    android/JSObject.cpp
    android/JSString.cpp
    android/JSValue.cpp
)

list(APPEND JavaScriptCore_LIBRARIES
    ${ANDROID_LOG_LIBRARY}
    ${ICU_LIBRARIES}
    ${ICU_I18N_LIBRARIES}
    ${ICU_DATA_LIBRARIES}
)

if (NOT LINK_ICU_DATA)
    list(APPEND JavaScriptCore_LIBRARIES
        WTF${DEBUG_SUFFIX}
    )
endif()

list(APPEND JavaScriptCore_SYSTEM_INCLUDE_DIRECTORIES
    ${GLIB_INCLUDE_DIRS}
    ${ICU_INCLUDE_DIRS}
    ${WTF_DIR}
)

install(FILES DESTINATION)

